# Generated by Django 3.2.16 on 2023-08-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230805_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created_at',), 'verbose_name': 'коментарий', 'verbose_name_plural': 'коментарии'},
        ),
    ]
